version: '3.7'

services:
  api:
    build:
      context: ./backend
    volumes:
      - django_static:/static
      - django_media:/media
    env_file:
      - ./backend/.env
    depends_on:
      - db_pierko

  db_pierko:
    image: postgres:12.0-alpine
    volumes:
      - pg_data:/var/lib/postgresql/data/
    env_file:
      - ./postgres/.env

  nginx:
    restart: unless-stopped
    build: .
    volumes:
     - django_static:/app/django_files/static
     - django_media:/app/django_files/media
     - ./nginx/production:/etc/nginx/conf.d
     - ./nginx/certbot/conf:/etc/letsencrypt
     - ./nginx/certbot/www:/var/www/certbot
    ports:
      - "83:83"
      - "443:443"
    depends_on:
      - api

  certbot:
    image: certbot/certbot
    restart: unless-stopped
    volumes:
      - ./nginx/certbot/conf:/etc/letsencrypt
      - ./nginx/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait

volumes:
  django_static:
  django_media:
  pg_data:

