version: '3.7'

services:
  api:
    build:
      context: ./backend
    volumes:
      - static:/static
      - media:/media
    env_file:
      - ./backend/.env
    ports:
      - "8000:8000"
      
  db_pierko:
    image: postgres:12.0-alpine
    volumes:
      - pg_data:/var/lib/postgresql/data/
    env_file:
      - ./postgres/.env
    ports:
      - "5434:5432"
  nginx:
    build: ./nginx
    volumes:
     - static:/static
     - media:/media
    ports:
      - "82:82"
    depends_on:
      - api

volumes:
  static:
  media:
  pg_data:
