# Generated by Django 3.1.3 on 2020-11-18 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=24)),
                ('details', models.TextField(max_length=350)),
                ('gallery_image', models.ImageField(upload_to='files/gallery_images/')),
                ('show', models.BooleanField(default=True)),
            ],
        ),
    ]
