# Generated by Django 3.1 on 2020-11-28 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pierko_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=32)),
                ('text', models.TextField(max_length=600)),
                ('gallery_image', models.ImageField(upload_to='files/article_images/')),
                ('position', models.CharField(choices=[('flex-start', 'Left'), ('flex-end', 'Right')], max_length=12)),
            ],
        ),
    ]
