# Generated by Django 3.1 on 2020-11-28 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pierko_api', '0002_articles'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articles',
            old_name='gallery_image',
            new_name='article_image',
        ),
    ]
